r"""

First, consider the free graded commutative algebra :math:`\bigwedge(t_0,\dots,t_n,y_0,\dots,y_n)`, where
the generators :math:`t_i` have degree :math:`0`, and the generators :math:`y_j` have degree :math:`1`.
The differential :math:`d` is given by

.. math::

    \begin{array}{rcl}
        d(t_i) &=& y_i, \\
        d(y_j) &=& 0.
    \end{array}


The cochain algebra :math:`(A_{PL})_{n}` is defined as the quotient:

.. math::

    (A_{PL})_n:=\frac{\bigwedge(t_0,\dots,t_n,y_0,\dots,y_n)}{\langle\sum {t_i}-1,\sum{y_j}\rangle}.

The implementation of this algebra has been made taking into account that this algebra is equivalent
to the exterior algebra :math:`Ext_y=\frac{\bigwedge(y_0,\dots,y_n)}{\langle\sum{y_j}\rangle}` with coefficients
in the polynomial ring :math:`R_t:=\frac{\mathbb{Q}[t_0,\dots,t_n]}{\langle\sum {t_i}-1\rangle}`:

.. math::

    (A_{PL})_n:=R_t \otimes Ext_y.

For that reason, :math:`R_t` is considered the base_ring of :math:`(A_{PL})_n`.

.. NOTE::

    Notice that this algebra is actually isomorphic to :math:`\bigwedge(t_1,\ldots,t_n,y_1,\ldots,y_n)`. That
    is, the relations allow us to express :math:`t_0` in terms of :math:`t_1,\ldots, t_n` and :math:`y_0` in terms of
    :math:`y_1,\ldots, y_n`. After eliminating :math:`t_0,y_0`, the expression of each element is unique. However,
    it is sometimes more convenient to use also :math:`t_0,y_0` to write certain formulas, so we will use one
    expression or the other depending on the context.

AUTHORS:

- Carlos Alquézar (2026-06-01): Beta version released

"""
# ****************************************************************************
#       Copyright (C) 2026 Carlos Alquézar <alquezar@unizar.es>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#                  https://www.gnu.org/licenses/
# ****************************************************************************

from sage.structure.unique_representation import UniqueRepresentation, CachedRepresentation
from sage.misc.cachefunc import cached_method, cached_function
from sage.structure.parent import Parent
from sage.structure.element import Element
from sage.algebras.clifford_algebra import ExteriorAlgebra
from sage.misc.latex import latex
from sage.rings.polynomial.polynomial_ring_constructor import PolynomialRing
from sage.rings.integer_ring import ZZ
from sage.rings.rational_field import QQ
from sage.combinat.free_module import CombinatorialFreeModule
from sage.sets.set import Set
from sage.matrix.constructor import vector, matrix, zero_matrix, identity_matrix
from sage.combinat.subset import powerset
from sage.all import cartesian_product
import copy
import itertools
from math import prod, factorial


class AplN(ExteriorAlgebra, UniqueRepresentation, CachedRepresentation):
    r"""
    The Algebra of polynomial differential forms.

    INPUT:

    - ``n`` -- dimension

    - ``labels`` -- (optional, default: ``t_i, y_i``); labels of the generators

    .. tab:: Sage

        EXAMPLES::

            sage: A = AplN(5)
            sage: A
            The Commutative Differential Graded Algebra (A_{PL})_{5} defined as
            the  tensor product of the Polynomial Ring QQ<t_{0},...,t_{5}> with
            the Exterior Algebra generated by QQ<y_{0},...,y_{5}>.

            The degrees of the generators are:

                deg(t_i)=0
                deg(y_j)=1

            The differential 'd' is defined as:

                d(t_i)=y_i
                d(y_j)=0

            sage: A.inject_variables()
            Defining y0, y1, y2, y3, y4, y5
            sage: R = A.base_ring()
            sage: R.inject_variables()
            Defining t0, t1, t2, t3, t4, t5
            sage: p = t1*y2*y3 + t0**2*y4*y5
            sage: p
            t1*y2*y3 + t0^2*y4*y5

    .. tab:: Raw code

        EXAMPLES::

            A = AplN(5)
            A.inject_variables()
            R = A.base_ring()
            R.inject_variables()
            p = t1*y2*y3 + t0**2*y4*y5

            labs = ('t2','t5','t6','y2','y5','y6')
            A = AplN(n=2,labels=labs)
            R = A.base_ring()
            A.inject_variables()
            R.inject_variables()


    """
    def __init__(self, n, labels=[]):
        r"""
        Initialize ``self``.

        INPUT:

        - ``n`` -- dimension

        - ``labels`` -- (optional, default: ``t_i, y_i``); labels of the generators

        .. tab:: Sage

            EXAMPLES::

                sage: A = AplN(5)
                sage: A
                The Commutative Differential Graded Algebra (A_{PL})_{5} defined as
                the  tensor product of the Polynomial Ring QQ<t_{0},...,t_{5}> with
                the Exterior Algebra generated by QQ<y_{0},...,y_{5}>.

                The degrees of the generators are:

                    deg(t_i)=0
                    deg(y_j)=1

                The differential 'd' is defined as:

                    d(t_i)=y_i
                    d(y_j)=0

                sage: A.inject_variables()
                Defining y0, y1, y2, y3, y4, y5
                sage: R = A.base_ring()
                sage: R.inject_variables()
                Defining t0, t1, t2, t3, t4, t5
                sage: p = t1*y2*y3 + t0**2*y4*y5
                sage: p
                t1*y2*y3 + t0^2*y4*y5


                sage: labs = ('t2','t5','t6','y2','y5','y6')
                sage: A = AplN(n=2,labels=labs)
                sage: R = A.base_ring()
                sage: A.inject_variables()
                Defining y2, y5, y6
                sage: R.inject_variables()
                Defining t2, t5, t6

        .. tab:: Raw code

            EXAMPLES::

                A = AplN(5)
                A.inject_variables()
                R = A.base_ring()
                R.inject_variables()
                p = t1*y2*y3 + t0**2*y4*y5

                labs = ('t2','t5','t6','y2','y5','y6')
                A = AplN(n=2,labels=labs)
                R = A.base_ring()
                A.inject_variables()
                R.inject_variables()

        """
        if (n < 0):
            raise ValueError('`n` must be a non-negative integer')
        if (labels and (not ((2 * (n + 1)) == len(labels)))):
            raise ValueError(
                (('`labels` must have length `' + str((n + 1))) + '`'))
        self.n = n
        self.name = ('Apl' + str(n))
        self._reduced_basis = {}
        self._reduced_monomials = {}
        self._multiplication_tables = {}
        self._multiplication_table_indexes = {}
        self._multiplication_table_sgns = {}
        self._graded_module_endomorphisms = {}
        if labels:
            ts = labels[:(n + 1)]
            ys = labels[(n + 1):]
            self.labels = labels
        else:
            ts = [('t' + str(t)) for t in range((n + 1))]
            ys = [('y' + str(t)) for t in range((n + 1))]
            self.labels = tuple(range((n + 1)))
        base_ring = PolynomialRing(QQ, names=ts)
        ExteriorAlgebra.__init__(self, base_ring, names=ys)

    @cached_method(do_pickle=True)
    def _basis_indexes(self, deg):
        r"""
        Considering ``self`` as a graded module, and serializing the basis of all modules up to degree ``deg``,
        this method returns the indexes corresponding to the elements of degree ``deg``.

        INPUT:

        - ``deg`` -- integer;

        OUTPUT: a tuple of indexes with format (start, end).

        .. tab:: Sage

            EXAMPLES::

        """
        nGens = [len(self.basis(d)) for d in range((self.n + 2))]
        cumsum = [0]
        for g in nGens:
            cumsum.append((cumsum[(- 1)] + g))
        if (deg == (self.n + 1)):
            return (cumsum[deg], None)
        else:
            return (cumsum[deg], cumsum[(deg + 1)])

    @cached_method(do_pickle=True)
    def _differential(self, p):
        r"""
        Return the differential of ``p``.

        .. tab:: Sage

            EXAMPLES::

                sage: A = AplN(5)
                sage: R = A.base_ring()
                sage: A.inject_variables()
                Defining y0, y1, y2, y3, y4, y5
                sage: R.inject_variables()
                Defining t0, t1, t2, t3, t4, t5
                sage: p = t0*t2*y2*y3
                sage: p.differential()
                t2*y0*y2*y3

        .. tab:: Raw code

            EXAMPLES::

                A = AplN(5)
                R = A.base_ring()
                A.inject_variables()
                R.inject_variables()
                p = t0*t2*y2*y3
                p.differential()

        """
        R = self.base_ring()
        d = self.zero()
        for term in p.terms():
            coeff = term.leading_coefficient()
            mon = term.leading_monomial()
            deriv_sum = sum([(R.derivation(t)(coeff) * y)
                            for (t, y) in zip(R.gens(), self.gens())])
            d += (deriv_sum * mon)
        return d

    @cached_method(do_pickle=True)
    def _differential_matrix(self, deg_y, deg_t):
        r"""
        Considering ``self`` as a graded module with coefficients in a polynomial ring,
        and serializing the basis of all modules up to degree ``deg_y`` with coefficients
        up to degree ``deg_t``., this method returns the differential matrix as a linear map
        between vector spaces.

        INPUT:

        - ``deg_t`` -- integer; maximum degree of the coefficients

        - ``deg_y`` -- integer; the degree of the differential domain

        OUTPUT: a matrix representing the differential as a linear map between vector spaces

        .. tab:: Sage

            EXAMPLES::

                sage: A = AplN(2)
                sage: print(A.extended_basis(deg_t=2,deg_y=0,cum=True))
                [1, t0, t0*t1, t0*t2, t0^2, t1, t1*t2, t1^2, t2, t2^2]
                sage: len(A.extended_basis(deg_t=2,deg_y=0,cum=True))
                10
                sage: print(A.extended_basis(deg_t=1,deg_y=1,cum=True))
                [t0*y0, t0*y1, t0*y2, t1*y0, t1*y1, t1*y2, t2*y0, t2*y1, t2*y2, y0, y1, y2]
                sage: len(A.extended_basis(deg_t=1,deg_y=1,cum=True))
                12
                sage: m = A._differential_matrix(deg_t=1,deg_y=1)
                sage: m.dimensions()
                (12, 10)
                sage: m
                [0 0 0 0 2 0 0 0 0 0]
                [0 0 1 0 0 0 0 0 0 0]
                [0 0 0 1 0 0 0 0 0 0]
                [0 0 1 0 0 0 0 0 0 0]
                [0 0 0 0 0 0 0 2 0 0]
                [0 0 0 0 0 0 1 0 0 0]
                [0 0 0 1 0 0 0 0 0 0]
                [0 0 0 0 0 0 1 0 0 0]
                [0 0 0 0 0 0 0 0 0 2]
                [0 1 0 0 0 0 0 0 0 0]
                [0 0 0 0 0 1 0 0 0 0]
                [0 0 0 0 0 0 0 0 1 0]

        """
        extb1 = self.extended_basis(
            deg_y=(deg_y - 1), deg_t=(deg_t + 1), cum=True)
        extb2 = self.extended_basis(deg_y=deg_y, deg_t=deg_t, cum=True)
        m = matrix(QQ, len(extb1), len(extb2), [g.differential()._to_extended_graded_module(
            deg_y=deg_y, deg_t=deg_t).to_vector() for g in extb1], sparse=True)
        return m.T

    @cached_method(do_pickle=True)
    def _free_graded_module(self, deg):
        r"""
        Return the graded module of ``self`` of degree ``deg`` with coefficients
        in the polynomial ring :math:`\mathbb{Q}[t_0,\dots,t_n`.

        INPUT:

        - ``deg`` -- integer

        OUTPUT: a CombinatorialFreeModule with coefficient in the base_ring of ``self``.

        .. tab:: Sage

            EXAMPLES::

                sage: A = AplN(2)
                sage: A._free_graded_module(2)
                Free module generated by {'y0y1', 'y0y2', 'y1y2'} over Multivariate Polynomial Ring in t0, t1, t2 over Rational Field

        """
        R = self.base_ring()
        gens = [str(g).replace('*', '') for g in list(self.basis(deg))]
        return CombinatorialFreeModule(R, gens, names=gens)

    @cached_method(do_pickle=True)
    def _from_extended_graded_module(self, p, deg_y, deg_t=1, cum=False):
        r"""
        Returns the element of ``self`` represented by ``p``.

        INPUT:

        - ``p`` -- an element of the extended graded module of degrees ``deg_y`` and ``deg_t``.

        - ``deg_y`` -- integer; degree of the module parent of ``p``

        - ``deg_t`` -- integer (default: `1`);

        - ``cum`` -- boolean (default: `False`); If ``True``, the extended basis will be used.

        OUTPUT: an element of self

        .. tab:: Sage

            EXAMPLES::

                sage: A = AplN(2)
                sage: C = A._free_graded_module(2)
                sage: p = C.an_element()
                sage: p
                2*y0y1 + 2*y0y2 + 3*y1y2
                sage: p in C
                True
                sage: p in A
                False
                sage: q = A._from_extended_graded_module(p,deg_y=2, deg_t=0,cum=False)
                sage: q
                2*y0*y1 + 2*y0*y2 + 3*y1*y2
                sage: q in A
                True
                sage: q in C
                False

        """
        R = self.base_ring()
        ext_basis = self.extended_basis(deg_y, deg_t, cum)
        return sum(((coef * gen) for (coef, gen) in zip(p.to_vector(), ext_basis)))

    @cached_method(do_pickle=True)
    def _from_graded_module(self, deg, p):
        r"""
        Returns the element of ``self`` represented by ``p`` on the underlying graded module.

        INPUT:

        - ``deg`` -- integer; degree of the module parent of ``p``

        - ``p`` -- an element of the graded module of degree ``deg``.

        OUTPUT: an element of self.

        .. tab:: Sage

            EXAMPLES::

                sage: A = AplN(2)
                sage: C = A._free_graded_module(2)
                sage: p = C.an_element()
                sage: p
                2*y0y1 + 2*y0y2 + 3*y1y2
                sage: p in C
                True
                sage: p in A
                False
                sage: deg = 2
                sage: q = A._from_graded_module(deg,p)
                sage: q
                2*y0*y1 + 2*y0*y2 + 3*y1*y2
                sage: q in C
                False
                sage: q in A
                True

        """
        gens = list(self.basis(deg))
        return sum(((coef * gen) for (coef, gen) in zip(p.to_vector(), gens)))

    @cached_method(do_pickle=True)
    def _graded_face_matrix(self, yi, deg):
        r"""
        Return the reduction matrix of the variable ``yi`` as a linear map
        between the graded vector spaces of degree ``deg`` of ``self`` and
        the graded vector space of the exterior subalgebra generated by all
        generators of ``self`` minus ``yi``:

        .. math::

            \bigwedge^deg(y_0,\dots,y_n) \longrightarrow  \bigwedge^deg(y_0,\dots,\hat{y}_i,\dots,y_n)

        INPUT:

        - ``yi`` -- integer;

        - ``deg`` -- integer;

        OUTPUT: sparse matrix;

        .. tab:: Sage

            EXAMPLES::

                sage: A = AplN(3)
                sage: list(A.basis(2))
                [y0*y1, y0*y2, y0*y3, y1*y2, y1*y3, y2*y3]
                sage: list(A.reduced_exterior_basis(yi=0, deg=2))
                [y1*y2 + y1*y3, -y1*y2 + y2*y3, -y1*y3 - y2*y3, y1*y2, y1*y3, y2*y3]
                sage: A._graded_face_matrix(yi=0,deg=2)
                [ 1 -1  0  1  0  0]
                [ 1  0 -1  0  1  0]
                [ 0  1 -1  0  0  1]

        """
        indices = self._reduction_indices(yi, deg)
        grad_reduction_matrix = self._graded_reduction_matrix(yi, deg)
        return grad_reduction_matrix[indices, :]

    @cached_method(do_pickle=True)
    def _graded_reduction_matrix(self, yi, deg):
        r"""

        Return the reduction matrix of the variable ``yi`` as a linear endomorphism
        of the graded vector space of degree ``deg``.

        INPUT:

        - ``yi`` -- integer;

        - ``deg`` -- integer;

        OUTPUT: sparse matrix;

        .. tab:: Sage

            EXAMPLES::

                sage: A = AplN(3)
                sage: list(A.basis(2))
                [y0*y1, y0*y2, y0*y3, y1*y2, y1*y3, y2*y3]
                sage: list(A.reduced_exterior_basis(yi=0, deg=2))
                [y1*y2 + y1*y3, -y1*y2 + y2*y3, -y1*y3 - y2*y3, y1*y2, y1*y3, y2*y3]
                sage: A._graded_face_matrix(yi=0,deg=2)
                [ 1 -1  0  1  0  0]
                [ 1  0 -1  0  1  0]
                [ 0  1 -1  0  0  1]


        """
        if (not (0 <= yi <= self.n)):
            raise ValueError(
                f'the reduction index must be an integer in the range {{0,{self.n}}}')
        if (not (1 <= deg <= (self.n + 1))):
            raise ValueError(
                f'the degree must be an integer in the range {{1,{(self.n + 1)}}}')
        if (deg == (self.n + 1)):
            return zero_matrix(self.base_ring(), 1)
        basis = self.basis(deg)
        v = [g.reduce(yi)._to_graded_module().to_vector() for g in basis]
        return matrix(self.base_ring(), v, sparse=True).T

    @cached_method(do_pickle=True)
    def _koszul_differential(self, p):
        r"""
        Return the koszul differential of `p`.

        For the :math:`q`--form :math:`\omega \in (A_{PL})^q_n`:

        .. math::
            \omega = p(\overline{t}) \;y_{j_0} \wedge\cdots\wedge y_{j_{q-1}}

        the koszul differential :math:`\kappa: (A_{PL})^q_n \rightarrow (A_{PL})^{q-1}_n` is defined as

        .. math::

            \kappa (\omega) = p(\overline{t}) \sum_{j=0}^{q-1}(-1)^{j}t_{i_j}y_{i_0}\wedge\cdots\wedge\hat{y_{i_j}}\wedge\cdots\wedge y_{j_{q-1}}

        where :math:`p(\overline{t}) \in \mathbb{Q}[t_0,\dots,t_n]`.

        Let :math:`\omega,\theta \in (A_{PL})_n`, and :math:`\omega` defined as before such that
        :math:`q=|\omega|`, and :math:`r=|p(\overline{t})|`. Then, the koszul differential has the properties:

            - :math:`\kappa \circ \kappa = 0`,

            - :math:`(\kappa \circ d)(\omega) + (d \circ \kappa)(\omega) = (r+q)\omega`,

            - :math:`\kappa(\omega \wedge \theta ) = \kappa(\omega) \wedge \theta + (-1)^{|\omega|} \omega \wedge \kappa (\theta)`.

        INPUT:

        - ``p`` -- a differential :math:`q`--form

        OUTPUT: a differential :math:`(q-1)`--form.

        .. tab:: Sage

            EXAMPLES::

                This example illustrates the relation between the differential and koszul operators::

                    sage: A = AplN(3)
                    sage: R = A.base_ring()
                    sage: A.inject_variables()
                    Defining
                    y0, y1, y2, y3
                    sage: R.inject_variables()
                    Defining
                    t0, t1, t2, t3
                    sage: p = t0 * t2 * y2 * y3
                    sage: p
                    t0*t2*y2*y3
                    sage: p.koszul().differential()+p.differential().koszul()
                    4*t0*t2*y2*y3
                    sage: (p.differential().koszul()+p.koszul().differential()).reduce(0) == (2+2)*p.reduce(0)
                    True
                    sage: p = t0*t2*y2*y3 + y1
                    sage: p.koszul().differential()+p.differential().koszul()
                    4*t0*t2*y2*y3 + y1

                This example illustrates the koszul differential of a wedge of forms::

                    sage: A = AplN(4)
                    sage: R = A.base_ring()
                    sage: A.inject_variables()
                    Defining y0, y1, y2, y3, y4
                    sage: R.inject_variables()
                    Defining t0, t1, t2, t3, t4
                    sage: p = t1*y2
                    sage: q = t2*y3*y4
                    sage: print(p.koszul()*q+((-1)**p.degree())*p*q.koszul().reduce(0) == (p*q).koszul().reduce(0))
                    True
                    sage: print(p.koszul().differential()+ p.differential().koszul() == (1+1)*p)
                    True
                    sage: print(q.koszul().differential()+ q.differential().koszul() == (1+2)*q)
                    True
        """
        R = self.base_ring()
        k = self.zero()
        for term in self(p).terms():  # (self(p) is used just in case p is of degree 0, i.e., an element of R
            mon = term.leading_monomial()  # monomial in the exterior algebra QQ<y_0,..,y_n>
            coef = term.coefficients()[0]
            dif = self.zero()
            for i, (t, y) in enumerate(zip(R.gens(), self.gens())):
                intprod = mon.interior_product(y)
                if intprod:
                    # interior product takes into account the sign
                    dif += self(t) * intprod
            k += coef * dif
        return k

    @cached_method(do_pickle=True)
    def _reduce_coeff_endomorphism(self, i):
        r"""
        Return the endomorphism of the base_ring of ``self`` that applies
        the relation :math:``t_i = 1-\sum_{j \neq i} t_j``.

        INPUT:

        - ``i`` -- integer;

        OUTPUT: a endomorphism of the base_ring of ``self``.

        .. tab:: Sage

            EXAMPLES::

                sage: A = AplN(4)
                sage: R = A.base_ring()
                sage: R.inject_variables()
                Defining t0, t1, t2, t3, t4
                sage: hom0 = A._reduce_coeff_endomorphism(i=0)
                sage: hom1 = A._reduce_coeff_endomorphism(i=1)
                sage: p = t1
                sage: hom0(p)
                t1
                sage: hom1(p)
                -t0 - t2 - t3 - t4 + 1
                sage: p = 1-t0-t1-t2-t3-t4
                sage: hom0(p)
                0
                sage: hom1(p)
                0

        """
        R = self.base_ring()
        gens = list(R.gens())
        gens.pop(i)
        image = list(gens)
        image.insert(i, (1 - sum(image)))
        return R.hom(image, R)

    @cached_method(do_pickle=True)
    def _reduce_monomial(self, monomial, i, deg):
        r"""
        Returns the result of applying the relation :math:`y_i = -\sum_{j \neq i} y_j`.

        INPUT:

        - ``monomial`` -- an monomial

        - ``i`` -- integer

        - ``deg`` -- integer

        OUTPUT: tuple; further description of the output

        .. tab:: Sage

            EXAMPLES::

                sage: A = AplN(5)
                sage: R = A.base_ring()
                sage: A.inject_variables()
                Defining y0, y1, y2, y3, y4, y5
                sage: R.inject_variables()
                Defining t0, t1, t2, t3, t4, t5
                sage: w = y1*y2
                sage: A._reduce_monomial(w,0,2)
                y1*y2
                sage: A._reduce_monomial(w,1,2)
                -y0*y2 + y2*y3 + y2*y4 + y2*y5
                sage: w = t1*y2
                sage: A._reduce_monomial(w,1,1)
                t1*y2
                sage: A._reduce_monomial(w,2,1)
                -t1*y0 - t1*y1 - t1*y3 - t1*y4 - t1*y5
                sage: w = y1 + y2
                sage: A._reduce_monomial(w,2,1)
                -y0 - y3 - y4 - y5
                sage: w = y1 + y2*y3
                sage: A._reduce_monomial(w,2,1)
                y2*y3 + y1
                sage: A._reduce_monomial(w,1,1)
                y2*y3 - y0 - y2 - y3 - y4 - y5
                sage: A._reduce_monomial(w,2,2)
                -y0*y3 - y1*y3 + y3*y4 + y3*y5 + y1

        """
        cache = self._reduced_monomials
        if (deg not in cache):
            cache[deg] = {}
        if (i not in cache[deg]):
            cache[deg][i] = {}
        if (monomial not in cache[deg][i]):
            red_map = self.graded_module_endomorphism(i, deg)
            (from_idx, to_idx) = self._basis_indexes(deg)
            v = monomial.to_vector()
            v_part = v[from_idx:to_idx]
            v_new_part = (red_map * v_part)
            v_new = v[:]
            v_new[from_idx:to_idx] = v_new_part
            reduced = self.from_vector(v_new)
            cache[deg][i][monomial] = reduced
        return cache[deg][i][monomial]

    @cached_method(do_pickle=True)
    def _reduction_indices(self, yi, deg):
        r"""
        Returns the indices of the graded module basis of degree ``deg``
        corresponding to generators NOT containing ``yi``.

        Equivalently, the method returns the nonzero positions of the
        ordered graded module basis of degree ``deg`` after substituting
        :math:`yi=0`.

        INPUT:

        - ``yi`` -- integer; the index of the exterior algebra generator

        - ``deg`` -- integer; the degree of the graded module

        OUTPUT: tuple of non-negative integers;

        .. tab:: Sage

            EXAMPLES::

                sage: A = AplN(3)
                sage: list(A.basis(2))
                [y0*y1, y0*y2, y0*y3, y1*y2, y1*y3, y2*y3]
                sage: A._reduction_indices(yi=1,deg=2)
                [1, 2, 5]

        """
        indices = [idx for idx in powerset(
            range((self.n + 1))) if ((len(idx) == deg) and (yi not in idx))]
        prods = [self.prod((self.gens()[i] for i in idx)) for idx in indices]
        basis_list = list(self.basis(deg))
        return sorted((basis_list.index(p) for p in prods))

    def _repr_(self):
        r"""
        Representation of 'self'.

        .. tab:: Sage

            EXAMPLES::

                sage: from Sullivan_MM import *
                sage: A = AplN(5)
                sage: A
                The Commutative Differential Graded Algebra (A_{PL})_{5} defined as
                the  tensor product of the Polynomial Ring QQ<t_{0},...,t_{5}> with
                the Exterior Algebra generated by QQ<y_{0},...,y_{5}>.

                The degrees of the generators are:

                    deg(t_i)=0
                    deg(y_j)=1

                The differential 'd' is defined as:

                    d(t_i)=y_i
                    d(y_j)=0

        """
        if (self.n <= 3):
            latex_extAlgGens = latex(self.gens()).replace(
                ' ', '').replace('\\left(', '').replace('\\right)', '')
            latex_polRingGens = latex(self.base_ring().gens()).replace(
                ' ', '').replace('\\left(', '').replace('\\right)', '')
        else:
            latex_extAlgGens = ((str(latex(self.gens()[
                                0])) + str(',...,')) + str(latex(self.gens()[(- 1)]))).replace(' ', '')
            latex_polRingGens = ((str(latex(self.base_ring().gens()[
                                 0])) + str(',...,')) + str(latex(self.base_ring().gens()[(- 1)]))).replace(' ', '')
        text = """The Commutative Differential Graded Algebra (A_{PL})_{""" + str(self.n) + """} defined as 
the  tensor product of the Polynomial Ring QQ<""" + latex_polRingGens + """> with 
the Exterior Algebra generated by QQ<""" + latex_extAlgGens + """>.

The degrees of the generators are:

    deg(t_i)=0
    deg(y_j)=1

The differential 'd' is defined as:

    d(t_i)=y_i
    d(y_j)=0
        """
        return text

    # def dupont_differential(self, p):
    #     dim = self.n
    #     dupdif = self.zero()
    #     for i in range((dim + 1)):
    #         dupdif += (self.dupont_operator(p, i) / (dim + 1))
    #     return dupdif
    @cached_method(do_pickle=True)
    def _dupont_operator(self, p, i):
        r"""
        This method implements the Dupont\'s operator :math:`h_n^i: (A_{PL})^{*}_{n} \rightarrow (A_{PL})^{*-1}_{n}`
        for the standard :math:`\Delta^n`-simplex as it is described in :cite:`cheng2008transferring`
        (see also :cite:`dupont1976simplicial`).

        Let :math:`\mathbb{K}` be a field of characteristic :math:`0` and let :math:`\Delta^n` be the
        standard :math:`n`-simplex. Also, let

        .. math::

            A_{PL}(\Delta^n) := \{A^p_{PL}(\Delta^n)\}_{p \geq 0},

        be the algebra of polynomial differential forms defined on :math:`\Delta^n`, where

        .. math::

            A^p_{PL}(\Delta^n) := \{ \sigma: \Delta^n \rightarrow (A_{PL})^p_n\}


        Notice that we can consider :math:`\Delta^n` as a set with only one element so, in this case

        .. math::

            A_{PL}(\Delta^n) \cong (A_{PL})_n.

        In fact, the motivation for the construction of :math:`(A_{PL})_n` was precisely to model locally
        the algebra of polynomial differential forms on simplices and, at the same time, construct a global
        structure satisfying the geometrical, topological and algebraic constraints. For the same reason,
        being :math:`C^*(\Delta^n)` the simplicial cochain complex of :math:`\Delta^n`, we have:

        .. math::
           :nowrap:

            \[
            C^p(\Delta^n)=\Biggl\{\begin{array}{cll}
            \mathbb{K}, &if \;\; p=n \\
            0, &  otherwise &
            \end{array}
            \]

        Let :math:`\int_n` be the de Rham map
        (see :cite:`Whitney1957GeometricIT, dupont1976simplicial, felix_rational_2001`):

        .. math::

            \int_n: (A_{PL})_n \rightarrow \mathbb{K}

        For a subset :math:`I = \{i_0,\dots,i_p\} \subseteq \{0,\dots,n\}`,
        with :math:`0 \leq i_0 < \cdots < i_p \leq n`, the Whitney map
        (see :cite:`Whitney1957GeometricIT, WhitneyFormsLOHI`)

        .. math::

            \mathcal{W}^I_n: \mathbb{K} \rightarrow (A_{PL})^p_n

        is defined as:

        .. math::

            \mathcal{W}^I_n(c) = c \cdot \sum_{j=0}^{p} (-1)^j t_{i_j} y_{i_0} \wedge \cdots \wedge \hat{y_{i_j}}
            \wedge \cdots \wedge y_{i_p}

        where :math:`\hat{}` means the term is omitted. The elements in the image of :math:`\mathcal{W}` are called
        the `elementary differential forms` or just `Whitney forms`.

        For a generic simplicial set :math:`S`, and following the work of Hassler `Whitney`
        (see :cite:`Whitney1957GeometricIT`), `Dupont` (see :cite:`dupont1976simplicial`) constructed an
        explicit simplicial contraction of the commutative differential graded algebra of polynomial differential forms
        :math:`A_{PL}(S)` to :math:`C^*(S)` compatible with the intrinsic affine structure of the polynomial
        differential forms (affine relations) and also with the wedge product of forms (up to homotopy).

        This method implements step by step the description of the contraction given
        by Cheng et al. (see :cite:`cheng2008transferring`) for the case of :math:`\Delta^n` (for the case of
        a general simplicial set go to :meth:`.dupont_contraction`), with minor notation adaptations
        for the sake of maintain coherence with the rest of the code.

        The description given by Cheng et al. is as follows:

            Let :math:`\omega \in (A_{PL})_n`. For each vertex :math:`e_i` of the :math:`n`-simplex :math:`\Delta^n`,
            define the dilation map

            .. math::

                \phi_i : [0,1] \times \Delta^n \to \Delta^n

            by the formula

            .. math::

                \phi_i(u,t_0, \dots, t_n) = ((1-u)t_0,\dots,(1-u)t_i+u,\dots,(1-u)t_n) .

            Let

            .. math::

                (\pi_i){}_*:A^*_{PL}([0,1]\times\Delta^n) \rightarrow (A_{PL})^{*-1}_n

            be integration over the first factor.

            The operator :math:`h_n^i`:

            .. math::

                h_n^i : (A_{PL})^{*}_n \rightarrow (A_{PL})^{*-1}_n

            is defined by the formula

            .. math::

                h_n^i\omega = (\pi_i)_* \phi_i^* \omega.

            where :math:`\phi_i^* \omega` is the pullback of :math:`\omega` respect to :math:`\phi_i`.

                Let

                .. math::

                    \epsilon_n^i: A^*_{PL}(\Delta^n) \rightarrow \mathbb{K}

                be evaluation at the vertex :math:`e_i`. The Poincar\'e Lemma states that

                .. math::

                    \mathbb{1}_{A} - \epsilon_n^i =  d \circ h_n^i + h_n^i \circ d .


        .. SEEALSO::

            :meth:`~AplN.Element.integral`

            :meth:`.whitney_form`

            :meth:`.dupont_contraction`

        .. REFERENCES::

            - :cite:`Whitney1957GeometricIT`

            - :cite:`dupont1976simplicial`

            - :cite:`cheng2008transferring`

            - :cite:`WhitneyFormsLOHI`

            - :cite:`felix_rational_2001`



        INPUT:

        - ``p`` -- an element of ``self``.

        - ``i`` -- integer; the vertex index to apply the operator

        OUTPUT: an element of ``self``;

        .. tab:: Sage

            EXAMPLES::

                sage: A = AplN(4)
                sage: R = A.base_ring()
                sage: A.inject_variables()
                Defining y0, y1, y2, y3, y4
                sage: R.inject_variables()
                Defining t0, t1, t2, t3, t4
                sage: w = t0*y1*y3
                sage: w.dif().dup(0) + w.dup(0).dif() == w
                True


        """
        def _face_coeff_endomorphism(dim):
            """
            Description

            """
            R = self.base_ring()
            RU = u_extension_t()
            return RU.hom(([R.zero()] + list(R.gens())), R)

        def face(pol):
            """
            Description

            """
            Au = pol.parent()
            dim = Au.n
            if (not pol.reduce(0)):
                return AplN((dim - 1)).zero()
            deg = Au(pol).degree()
            if (not (0 <= deg <= (dim + 1))):
                raise ValueError(
                    f'the degree must be an integer in the range {{1,{(dim + 1)}}}')
            hom = _face(deg)
            baseRingFaceHom = hom['base_ring_hom']
            B = AplN((dim - 1))
            if (Au(pol).degree() == 0):
                return B(baseRingFaceHom(Au(pol).leading_coefficient()))
            MB = B._free_graded_module(deg)
            face_hom = hom['graded_module_hom']
            new_element = B.zero()
            for term in pol.terms():
                c = term.leading_coefficient()
                m = term.leading_monomial()
                v = m._to_graded_module().to_vector()
                vb = MB.from_vector((face_hom * v))
                new_coeff = baseRingFaceHom(c)
                new_monomial = B._from_graded_module(deg, vb)
                new_element += (new_coeff * new_monomial)
            return new_element

        def _face(deg):
            """
            Description

            """
            face_idx = 0
            dim = (self.n + 1)
            if (not (0 <= deg <= (dim + 1))):
                raise ValueError(
                    f'the degree must be an integer in the range {{1,{(dim + 1)}}}')
            baseRingFaceHom = _face_coeff_endomorphism(dim)
            if (deg == 0):
                return {'base_ring_hom': baseRingFaceHom, 'graded_module_hom': {}}
            A = u_extension()
            #B = AplN((dim - 1))
            MA = A._free_graded_module(deg)
            #face_matrix = A._graded_face_matrix(face_idx, deg)
            #face_matrix = face_matrix.change_ring(QQ)
            idx = A._reduction_indices(face_idx, deg)
            m = identity_matrix(QQ, MA.dimension())
            face_hom = m[idx, :]
            return {'base_ring_hom': baseRingFaceHom, 'graded_module_hom': face_hom}

        def u_extension_t():
            """
            Description

            """
            R = self.base_ring()
            varnames = (['u'] + list(R.variable_names()))
            return PolynomialRing(QQ, names=varnames)

        def u_extension():
            """
            Description

            """
            A = self
            R = A.base_ring()
            tlabels = (['u'] + list(R.variable_names()))
            ylabels = (['du'] + list(A.variable_names()))
            labels = (tlabels + ylabels)
            return AplN((A.n + 1), labels=tuple(labels))

        def dilation_map_t(i):
            """
            Description

            """
            def inclusion(R, RU):
                """
                Description

                """
                return R.hom(RU.gens()[1:], RU)
            R = self.base_ring()
            RU = u_extension_t()
            u = RU.gens()[0]
            inc = inclusion(R, RU)
            tgens = [inc(t) for t in R.gens()]
            image = []
            for (j, t) in enumerate(tgens):
                if (not (i == j)):
                    image.append([((1 - u) * t)])
                else:
                    image.append([(((1 - u) * t) + u)])
            return R.hom(image, RU)

        def dilation_map_y(i):
            """
            Description

            """
            A = self
            R = A.base_ring()
            Au = u_extension()
            Ru = Au.base_ring()
            cols = []
            for t in R.gens():
                dt = Au(dilation_map_t(i)(t)).differential()
                cols.append(dt._to_graded_module().to_vector())
            m = matrix(Ru, (len(Au.gens()) - 1), cols).T
            return A.lift_morphism(m, names=Au.variable_names())

        def dilation_map(pol, i):
            """
            Description

            """
            A = self
            R = A.base_ring()
            Au = u_extension()
            Ru = Au.base_ring()
            dilt = dilation_map_t(i)
            dily = dilation_map_y(i)
            dilation = Au.zero()
            for term in pol.terms():
                coef = term.coefficients()[0]
                mon = term.monomials()[0]
                dilation += (dilt(coef) * Au(dily(mon)))
            return dilation

        def u_integration(pol):
            """
            Description

            """
            Au = pol.parent()
            Ru = Au.base_ring()
            u = Ru.gens()[0]
            du = Au.gens()[0]
            intp = Au.zero()
            for term in pol.interior_product(du).terms():
                coef = term.coefficients()[0]
                mon = term.monomials()[0]
                intcoef = (coef.integral(u).substitute(u=1) -
                           coef.integral(u).substitute(u=0))
                intp += (intcoef * mon)
            return intp

        def projection(pol):
            """
            Description

            """
            return face(pol)

        Au = u_extension()
        RU = Au.base_ring()
        u = RU.gens()[0]
        di = dilation_map(p, i)
        inti = u_integration(di)
        return projection(inti)

    @cached_method(do_pickle=True)
    def extended_basis(self, deg_y, deg_t=1, cum=False):
        r"""
        Considering ``self`` as a graded module, this method returns the
        module basis of degree ``deg_y`` with polynomial coefficients truncated
        by degree ``deg_t``.

        INPUT:

        - ``deg_y`` -- integer ; degree of the graded module of ``self``.

        - ``deg_t`` -- integer (default: `1`); coefficient\'s degree

        - ``cum`` -- boolean (default: `False`); If `True`, the basis takes into account
            polynomial coefficients up to degree ``deg_t``. Otherwise, the method returns
            the basis with homogeneous coefficients of degree ``deg_t``.

        OUTPUT: tuple of monomials of ``self``; module generators of exterior degree ``deg_y``.

        .. tab:: Sage

            EXAMPLES::

                sage: A = AplN(2)
                sage: A.extended_basis(deg_y=1,deg_t=1,cum=False)
                [t0*y0, t0*y1, t0*y2, t1*y0, t1*y1, t1*y2, t2*y0, t2*y1, t2*y2]
                sage: A.extended_basis(deg_y=1,deg_t=1,cum=True)
                [t0*y0, t0*y1, t0*y2, t1*y0, t1*y1, t1*y2, t2*y0, t2*y1, t2*y2, y0, y1, y2]

        .. tab:: Raw code

            EXAMPLES::

                A = AplN(2)
                A.extended_basis(deg_y=1,deg_t=1,cum=False)
                A.extended_basis(deg_y=1,deg_t=1,cum=True)


        """
        basis = []
        rgens = []
        R = self.base_ring()
        ext_basis = list(self.basis(deg_y))
        if cum:
            basis = ext_basis
            t_degrees = range((deg_t + 1))
        elif deg_t:
            t_degrees = [deg_t]
        else:
            return ext_basis
        for i in t_degrees:
            rgens += list(set([prod(l)
                          for l in itertools.product(R.gens(), repeat=i)]))
        CP = cartesian_product([rgens, ext_basis])
        basis += [prod(p) for p in CP]
        basis = list(set(basis))
        basis.sort(key=str)
        return basis

    @cached_method(do_pickle=True)
    def extended_graded_module(self, deg_y, deg_t=1, cum=False):
        r"""
        Return the extended graded module of ``self`` of degree ``deg_y`` with coefficients
        in the polynomial ring :math:`\mathbb{Q}[t_0,\dots,t_n]`.

        INPUT:

        - ``deg_y`` -- integer; degree of the graded module of ``self``.

        - ``deg_t`` -- integer (default: `1`); coefficient\'s degree.

        - ``cum`` -- boolean (default: `False`); If `True`, the basis takes into account
        polynomial coefficients up to degree ``deg_t``. Otherwise, the method returns
        the basis with homogeneous coefficients of degree ``deg_t``.

        OUTPUT: a CombinatorialFreeModule with coefficient in the base_ring of ``self``.

        .. tab:: Sage

            EXAMPLES::

                sage: A = AplN(2)
                sage: A.extended_graded_module(deg_y=1,deg_t=1,cum=True)
                Free module generated by {'t0y0', 't0y1', 't0y2', 't1y0', 't1y1', 't1y2', 't2y0', 't2y1', 't2y2', 'y0',
                'y1', 'y2'} over Multivariate Polynomial Ring in t0, t1, t2 over Rational Field

        """
        R = self.base_ring()
        ext_basis = self.extended_basis(deg_y, deg_t, cum)
        ext_basis.sort(key=str)
        gens = [str(g).replace('*', '') for g in ext_basis]
        gens = [g.replace('^', 'e') for g in gens]
        return CombinatorialFreeModule(R, gens, names=gens)

    @cached_method(do_pickle=True)
    def graded_module_endomorphism(self, yi, deg):
        r"""

        Return the reduction matrix of the variable ``yi`` as a linear endomorphism
        of the graded vector space of degree ``deg``.

        INPUT:

        - ``yi`` -- integer;

        - ``deg`` -- integer;

        OUTPUT: sparse matrix;

        .. tab:: Sage

            EXAMPLES::

                sage: A = AplN(3)
                sage: list(A.basis(2))
                [y0*y1, y0*y2, y0*y3, y1*y2, y1*y3, y2*y3]
                sage: list(A.reduced_exterior_basis(yi=0, deg=2))
                [y1*y2 + y1*y3, -y1*y2 + y2*y3, -y1*y3 - y2*y3, y1*y2, y1*y3, y2*y3]
                sage: A._graded_face_matrix(yi=0,deg=2)
                [ 1 -1  0  1  0  0]
                [ 1  0 -1  0  1  0]
                [ 0  1 -1  0  0  1]


        """

        def _graded_module_endomorphism(yi, deg):
            """
            Description

            """
            if (deg == (self.n + 1)):
                m = matrix(self.base_ring(), 1, [0])
            else:
                basis = self.reduced_exterior_basis(yi, deg)
                m = identity_matrix(self.base_ring(), len(basis), sparse=True)
                (from_idx, to_idx) = self._basis_indexes(deg)
                for (i, gen) in enumerate(basis):
                    v = gen.to_vector()[from_idx:to_idx]
                    m[:, i] = v
            self._graded_module_endomorphisms[(yi, deg)] = m
            return m

        if (not (0 <= yi <= self.n)):
            raise ValueError('yi must be in [0, n]')
        key = (yi, deg)
        if (key in self._graded_module_endomorphisms):
            return self._graded_module_endomorphisms[key]
        return _graded_module_endomorphism(yi, deg)

    # def hom(self, base_imgs, gens_imgs, codomain=None):
    #     if (codomain == None):
    #         codomain = self
    #     raise NotImplementedError

    # def inject_vars(self):
    #     self.base_ring().inject_variables()
    #     self.inject_variables()
    #     return None

    # def _load_data(self, data_path='./'):
    #     try:
    #         data = load(((data_path + self.name) + '_data'))
    #     except FileNotFoundError:
    #         print('No data available.', flush=True)
    #         return None
    #     if data:
    #         self._reduced_basis = data['_reduced_basis']
    #         self._reduced_monomials = data['_reduced_monomials']
    #         self._multiplication_tables = data['_multiplication_tables']
    #         self._multiplication_table_indexes = data['_multiplication_table_indexes']
    #         self._multiplication_table_sgns = data['_multiplication_table_sgns']
    #         self._graded_module_endomorphisms = data['_graded_module_endomorphisms']
    #     return None

    # def multiplication_table(self, deg1, deg2):
    #     key = (deg1, deg2)
    #     if (key in self._multiplication_tables):
    #         return self._multiplication_tables[key]
    #     basis1 = list(self.basis(deg1))
    #     basis2 = list(self.basis(deg2))
    #     m = matrix(self, len(basis1), len(basis2), sparse=True)
    #     for (i, a) in enumerate(basis1):
    #         for (j, b) in enumerate(basis2):
    #             m[(i, j)] = (a * b)
    #     self._multiplication_tables[key] = m
    #     return m
    @cached_method(do_pickle=True)
    def reduced_exterior_basis(self, yi, deg):
        r"""
        Returns the exterior basis of the homogeneous graded module of degree ``deg``
        after applying the relation :math:`y_i = -\sum_{j \neq i} y_j`.

        INPUT:

        - ``yi`` -- integer; the index of the exterior algebra generator

        - ``deg`` -- integer; the degree of the graded module

        OUTPUT: tuple of non-negative integers;

        .. tab:: Sage

            EXAMPLES::

                sage: A = AplN(4)
                sage: list(A.basis(1))
                [y0, y1, y2, y3, y4]
                sage: A.reduced_exterior_basis(yi=2, deg=1)
                (y0, y1, -y0 - y1 - y3 - y4, y3, y4)

        """
        def multiplication_table_indexes(deg1, deg2):
            """
            Description
            """
            key = (deg1, deg2)
            if (key in self._multiplication_table_indexes):
                return (self._multiplication_table_indexes[key], self._multiplication_table_sgns[key])
            basis_all = list(self.basis())
            deg = (deg1 + deg2)
            (from_idx, to_idx) = self._basis_indexes(deg)
            basis_deg = basis_all[from_idx:to_idx]
            basis1 = list(self.basis(deg1))
            basis2 = list(self.basis(deg2))
            m_idx = matrix(ZZ, len(basis1), len(basis2), sparse=True)
            m_sgn = matrix(ZZ, len(basis1), len(basis2), sparse=True)
            for (i, a) in enumerate(basis1):
                for (j, b) in enumerate(basis2):
                    prod = (a * b)
                    if prod.is_zero():
                        m_idx[(i, j)] = (- 1)
                    else:
                        mon = prod.monomials()[0]
                        coeff = prod.leading_coefficient()
                        m_idx[(i, j)] = basis_deg.index(mon)
                        m_sgn[(i, j)] = coeff
            self._multiplication_table_indexes[key] = m_idx
            self._multiplication_table_sgns[key] = m_sgn
            return (m_idx, m_sgn)

        def _reduce_exterior_basis(yi, deg):
            """
            Description
            """
            if (deg == 1):
                return self.reduced_exterior_basis(yi, 1)
            basis1 = list(self.reduced_exterior_basis(yi, 1))
            basis2 = list(self.reduced_exterior_basis(yi, (deg - 1)))
            full_basis = list(self.basis(deg))
            (idx_mat, sgn_mat) = multiplication_table_indexes(1, (deg - 1))
            nonZero = idx_mat.find((lambda entry: (entry != (- 1))))
            for (i, j) in nonZero.nonzero_positions():
                if (i < j):
                    prod = (basis1[i] * basis2[j])
                    full_basis[idx_mat[(i, j)]] = (sgn_mat[(i, j)] * prod)
            return tuple(full_basis)

        if (not (0 <= yi <= self.n)):
            raise ValueError('yi must be in [0, n]')
        if ((yi, deg) in self._reduced_basis):
            return self._reduced_basis[(yi, deg)]
        if (deg == 0):
            result = self.one()
        elif (deg == 1):
            reduced = list(self.basis(1))
            reduced.pop(yi)
            reduced.insert(yi, (- sum(reduced)))
            result = tuple(reduced)
        elif (deg == (self.n + 1)):
            result = self.zero()
        else:
            result = _reduce_exterior_basis(yi, deg)
        self._reduced_basis[(yi, deg)] = result
        return result

    # def _reset_data(self):
    #     self._reduced_basis = {}
    #     self._reduced_monomials = {}
    #     self._multiplication_tables = {}
    #     self._multiplication_table_indexes = {}
    #     self._multiplication_table_sgns = {}
    #     self._graded_module_endomorphisms = {}
    #     return None

    # def _save_data(self, data_path='./'):
    #     data = {'_reduced_basis': self._reduced_basis, '_reduced_monomials': self._reduced_monomials, '_multiplication_tables': self._multiplication_tables,
    #             '_multiplication_table_indexes': self._multiplication_table_indexes, '_multiplication_table_sgns': self._multiplication_table_sgns, '_graded_module_endomorphisms': self._graded_module_endomorphisms}
    #     save(data, ((data_path + self.name) + '_data'))
    #     return None

    # def solve_primitive(self, dp, deg_y, deg_t):
    #     r"""
    #     For a closed differential form, this method returns an element `q` such that
    #     :math:`d(q)=d(p)`.
    #
    #     INPUT:
    #
    #     - ``dp`` -- differential form
    #
    #     - ``deg_y`` -- integer; degree of `dp`
    #
    #     - ``deg_t`` -- integer; maximum degree on the base_ring to look for a primitive
    #
    #     OUTPUT: a differential form;
    #
    #     EXAMPLES::
    #
    #
    #     """
    #     dv = dp._to_extended_graded_module(deg_y=deg_y, deg_t=deg_t).to_vector()
    #     m = self._differential_matrix(deg_y, deg_t)
    #     v = m.solve_right(dv)
    #     C = self.extended_graded_module(
    #         deg_y=(deg_y - 1), deg_t=(deg_t + 1), cum=True)
    #     p = C.from_vector(v)
    #     return self._from_extended_graded_module(p, deg_y=(deg_y - 1), deg_t=(deg_t + 1), cum=True)
    @cached_method(do_pickle=True)
    def whitney_form(self):
        r"""
        Returns the `elementary volume form` (also called `constant volume form`)
        of ``self``. The Whitney volume form on :math:`(A_{PL})_n` if a differential
        form of degree `n` defined as:

        .. math::

            \omega_n = n! \cdot \sum_{k=0}^{n} (-1)^k t_{0} \cdot
            y_{0} \wedge \cdots \wedge \hat{y}_{k} \wedge \cdots \wedge y_{n}

        OUTPUT: a differential form of degree `n`;

        .. tab:: Sage

            EXAMPLES::

                sage: A = AplN(4)
                sage: A.whitney_form()
                24*t4*y0*y1*y2*y3 - 24*t3*y0*y1*y2*y4 + 24*t2*y0*y1*y3*y4 - 24*t1*y0*y2*y3*y4 + 24*t0*y1*y2*y3*y4
                sage: _.reduce(0)
                24*y1*y2*y3*y4

        """
        n = self.n
        R = self.base_ring()
        rgens = list(R.gens())
        w_form = self.zero()
        for i in range(len(rgens)):
            gens = list(self.gens())
            gens.pop(i)
            w_form += ((((- 1) ** i) * rgens[i]) * prod(gens))
        return (factorial(n) * w_form)

    class Element(ExteriorAlgebra.Element):
        r"""
        A polynomial differential form.
        """

        @cached_method(do_pickle=True)
        def _to_extended_graded_module(self, deg_y, deg_t):
            r"""
            Returns self as an element of the extended graded module defined by
            the parameters.

            INPUT:

            - ``deg_y`` -- integer;

            - ``deg_t`` -- integer

            OUTPUT:

            .. tab:: Sage

                EXAMPLES::

            .. SEEALSO::

                :meth:`.extended_graded_module`

            """
            A = self.parent()
            basis = A.extended_basis(deg_y=deg_y, deg_t=deg_t, cum=True)
            C = A.extended_graded_module(deg_y=deg_y, deg_t=deg_t, cum=True)
            v = vector(QQ, len(basis), sparse=True)
            if (not self):
                return sum([prod(i) for i in zip(v, C.gens())])
            for term in self.terms():
                y_mon = term.monomials()[0]
                coeff = term.coefficients()[0]
                for t_mon in coeff.monomials():
                    c = coeff.monomial_coefficient(t_mon)
                    g_idx = basis.index((t_mon * y_mon))
                    v[g_idx] = c
            return sum([prod(i) for i in zip(v, C.gens())])

        @cached_method(do_pickle=True)
        def _to_graded_module(self):
            r"""
            Returns ``self`` as a graded module element.

            .. tab:: Sage

                EXAMPLES::

            .. SEEALSO::

                :meth:`._free_graded_module`

            """
            deg = self.degree()
            A = self.parent()
            C = A._free_graded_module(deg)
            (from_idx, to_idx) = A._basis_indexes(deg)
            coeffs = self.to_vector()[from_idx:to_idx]
            return sum([prod(i) for i in zip(coeffs, C.gens())])

        @cached_method(do_pickle=True)
        def differential(self):
            r"""
            Return the differential of `self`.

            For the :math:`q`--form :math:`\omega \in (A_{PL})^q_n`:

            .. math::
                \omega = p(\overline{t}) \;y_{j_0} \wedge\cdots\wedge y_{j_{q-1}}

            the differential :math:`d: (A_{PL})^q_n \rightarrow (A_{PL})^{q+1}_n` is defined as

            .. math::

                d (\omega) =  \sum_{j=0}^{n} \frac{\partial p(\overline{t})}{\partial t_j}y_{j}\wedge y_{i_0}\wedge\cdots\wedge y_{j_{q-1}}

            where :math:`p(\overline{t}) \in \mathbb{Q}[t_0,\dots,t_n]`.

            Let :math:`\omega,\theta \in (A_{PL})_n`. Then, the differential has the properties:

                - :math:`d \circ d = 0`,

                - :math:`d(\omega \wedge \theta ) = d(\omega) \wedge \theta + (-1)^{|\omega|} \omega \wedge d (\theta)`.


            OUTPUT: a differential :math:`(q+1)` --form.

            .. tab:: Sage

                EXAMPLES::

                    sage: A = AplN(5)
                    sage: R = A.base_ring()
                    sage: A.inject_variables()
                    Defining y0, y1, y2, y3, y4, y5
                    sage: R.inject_variables()
                    Defining t0, t1, t2, t3, t4, t5
                    sage: p = t0*t2*y2*y3
                    sage: p.differential()
                    t2*y0*y2*y3

                    sage: A = AplN(5)
                    sage: R = A.base_ring()
                    sage: A.inject_variables()
                    Defining y0, y1, y2, y3, y4, y5
                    sage: R.inject_variables()
                    Defining t0, t1, t2, t3, t4, t5
                    sage: w = (t1*t2+t3**2)*y2*y3
                    sage: theta = t0*y4
                    sage: w.degree()
                    2
                    sage: w.differential()*theta+((-1)**2)*w*theta.differential() == (w*theta).differential()
                    True
                    sage: w.differential()
                    t2*y1*y2*y3
                    sage: w.differential().differential()
                    0

            .. tab:: Raw code

                EXAMPLES::

                    A = AplN(5)
                    R = A.base_ring()
                    A.inject_variables()
                    R.inject_variables()
                    p = t0*t2*y2*y3
                    p.differential()

                    A = AplN(5)
                    R = A.base_ring()
                    A.inject_variables()
                    R.inject_variables()
                    w = (t1*t2+t3**2)*y2*y3
                    theta = t0*y4
                    w.degree()
                    w.differential()*theta+((-1)**2)*w*theta.differential() == (w*theta).differential()
                    w.differential()
                    w.differential().differential()


            """
            return self.parent()._differential(self)

        # def dupont_differential(self):
        #     return self.parent().dupont_contraction(self)
        @cached_method(do_pickle=True)
        def dif(self):
            r"""
            Alias for :meth`self.differential`
            """
            return self.parent()._differential(self)

        @cached_method(do_pickle=True)
        def dup(self,i):
            r"""
            Alias for :meth:`dupont_operator`
            """
            return self.parent()._dupont_operator(self, i)

        @cached_method(do_pickle=True)
        def dupont_operator(self, i):
            r"""
            This method implements the Dupont\'s operator :math:`h_n^i: (A_{PL})^{*}_{n} \rightarrow (A_{PL})^{*-1}_{n}`
            for the standard :math:`\Delta^n`-simplex as it is described in :cite:`cheng2008transferring`
            (see also :cite:`dupont1976simplicial`).

            Let :math:`\mathbb{K}` be a field of characteristic :math:`0` and let :math:`\Delta^n` be the
            standard :math:`n`-simplex. Also, let

            .. math::

                A_{PL}(\Delta^n) := \{A^p_{PL}(\Delta^n)\}_{p \geq 0},

            be the algebra of polynomial differential forms defined on :math:`\Delta^n`, where

            .. math::

                A^p_{PL}(\Delta^n) := \{ \sigma: \Delta^n \rightarrow (A_{PL})^p_n\}


            Notice that we can consider :math:`\Delta^n` as a set with only one element so, in this case

            .. math::

                A_{PL}(\Delta^n) \cong (A_{PL})_n.

            In fact, the motivation for the construction of :math:`(A_{PL})_n` was precisely to model locally
            the algebra of polynomial differential forms on simplices and, at the same time, construct a global
            structure satisfying the geometrical, topological and algebraic constraints. For the same reason,
            being :math:`C^*(\Delta^n)` the simplicial cochain complex of :math:`\Delta^n`, we have:

            .. math::
               :nowrap:

                \[
                C^p(\Delta^n)=\Biggl\{\begin{array}{cll}
                \mathbb{K}, &if \;\; p=n \\
                0, &  otherwise &
                \end{array}
                \]

            Let :math:`\int_n` be the de Rham map
            (see :cite:`Whitney1957GeometricIT, dupont1976simplicial, felix_rational_2001`):

            .. math::

                \int_n: (A_{PL})_n \rightarrow \mathbb{K}

            For a subset :math:`I = \{i_0,\dots,i_p\} \subseteq \{0,\dots,n\}`,
            with :math:`0 \leq i_0 < \cdots < i_p \leq n`, the Whitney map
            (see :cite:`Whitney1957GeometricIT, WhitneyFormsLOHI`)

            .. math::

                \mathcal{W}^I_n: \mathbb{K} \rightarrow (A_{PL})^p_n

            is defined as:

            .. math::

                \mathcal{W}^I_n(c) = c \cdot \sum_{j=0}^{p} (-1)^j t_{i_j} y_{i_0} \wedge \cdots \wedge \hat{y_{i_j}}
                \wedge \cdots \wedge y_{i_p}

            where :math:`\hat{}` means the term is omitted. The elements in the image of :math:`\mathcal{W}` are called
            the `elementary differential forms` or just `Whitney forms`.

            For a generic simplicial set :math:`S`, and following the work of Hassler `Whitney`
            (see :cite:`Whitney1957GeometricIT`), `Dupont` (see :cite:`dupont1976simplicial`) constructed an
            explicit simplicial contraction of the commutative differential graded algebra of polynomial differential forms
            :math:`A_{PL}(S)` to :math:`C^*(S)` compatible with the intrinsic affine structure of the polynomial
            differential forms (affine relations) and also with the wedge product of forms (up to homotopy).

            This method implements step by step the description of the contraction given
            by Cheng et al. (see :cite:`cheng2008transferring`) for the case of :math:`\Delta^n` (for the case of
            a general simplicial set go to :meth:`.dupont_contraction`), with minor notation adaptations
            for the sake of maintain coherence with the rest of the code.

            The description given by Cheng et al. is as follows:

                Let :math:`\omega \in (A_{PL})_n`. For each vertex :math:`e_i` of the :math:`n`-simplex :math:`\Delta^n`,
                define the dilation map

                .. math::

                    \phi_i : [0,1] \times \Delta^n \to \Delta^n

                by the formula

                .. math::

                    \phi_i(u,t_0, \dots, t_n) = ((1-u)t_0,\dots,(1-u)t_i+u,\dots,(1-u)t_n) .

                Let

                .. math::

                    (\pi_i){}_*:A^*_{PL}([0,1]\times\Delta^n) \rightarrow (A_{PL})^{*-1}_n

                be integration over the first factor.

                The operator :math:`h_n^i`:

                .. math::

                    h_n^i : (A_{PL})^{*}_n \rightarrow (A_{PL})^{*-1}_n

                is defined by the formula

                .. math::

                    h_n^i\omega = (\pi_i)_* \phi_i^* \omega.

                where :math:`\phi_i^* \omega` is the pullback of :math:`\omega` respect to :math:`\phi_i`.

                    Let

                    .. math::

                        \epsilon_n^i: A^*_{PL}(\Delta^n) \rightarrow \mathbb{K}

                    be evaluation at the vertex :math:`e_i`. The Poincar\'e Lemma states that

                    .. math::

                        \mathbb{1}_{A} - \epsilon_n^i =  d \circ h_n^i + h_n^i \circ d .


            .. SEEALSO::

                :meth:`._dupont_operator`

                :meth:`.integral`

            .. REFERENCES::

                - :cite:`Whitney1957GeometricIT`

                - :cite:`dupont1976simplicial`

                - :cite:`cheng2008transferring`

                - :cite:`WhitneyFormsLOHI`

                - :cite:`felix_rational_2001`


            INPUT:

            - ``p`` -- an element of ``self``.

            - ``i`` -- integer; the vertex index to apply the operator

            OUTPUT: an element of ``self``;


            .. tab:: Sage

                EXAMPLES::

                    sage: A = AplN(4)
                    sage: R = A.base_ring()
                    sage: A.inject_variables()
                    Defining y0, y1, y2, y3, y4
                    sage: R.inject_variables()
                    Defining t0, t1, t2, t3, t4
                    sage: w = t0*y1*y3
                    sage: w.dup(0).dif()
                    -1/3*t3*y0*y1 + 1/3*t1*y0*y3 + (2/3*t0 + 1/3)*y1*y3
                    sage: w.dif().dup(0)
                    1/3*t3*y0*y1 - 1/3*t1*y0*y3 + (1/3*t0 - 1/3)*y1*y3
                    sage: w.dup(0).dif()+w.dif().dup(0) == w
                    True

            """
            return self.parent()._dupont_operator(self, i)

        @cached_method(do_pickle=True)
        def homogeneous_components(self):
            r"""
            Return the homogeneous components of ``self``.

            OUTPUT: a dictionary indexed by degree.

            .. tab:: Sage

                EXAMPLES::

                    sage: A = AplN(5)
                    sage: R = A.base_ring()
                    sage: A.inject_variables()
                    Defining y0, y1, y2, y3, y4, y5
                    sage: R.inject_variables()
                    Defining t0, t1, t2, t3, t4, t5
                    sage: p = t0*t2*y2*y3
                    sage: p = t0*t2*y2*y3 + y1
                    sage: p.homogeneous_components()
                    {1: y1, 2: t0*t2*y2*y3}

            """
            if (self.is_homogeneous() and (not self.is_zero())):
                return {self.degree(): self}
            elif self.is_zero():
                return {0: self}
            components = {}
            for d in range((self.parent().n + 1)):
                hcomp = self.homogeneous_component(d)
                if hcomp:
                    components[d] = hcomp
            return components

        @cached_method(do_pickle=True)
        def integral(self, yi=0):
            r"""
            Returns the integral of ``self``, defined as follows:

            Let :math:`\int_{n}` be the linear map:

            .. math::

                \int_{n}: (A_{PL})_{n}^{n} \rightarrow \mathbb{Q}

            by setting

            .. math::
               :nowrap:

                \begin{split}
                \int_{n}t_1^{k_1}\dots t_n^{k_n}dt_1 \wedge \dots \wedge dt_n &= \int_{0}^{1} dt_1\int_{0}^{1-t_1} dt_2 \dots\\
                &\dots \int_{0}^{1-\sum\limits_{1}^{n-1}t_i}t_1^{k_1}\dots t_n^{k_n}dt_n = \\
                &= \frac{k_1!k_2! \dots k_n!}{(k_1+ \dots +k_n+n)!}.
                \end{split}


            This map represents the integration :math:`\int_{\Delta^n}\omega` of an `n`-form
            :math:`\omega \in (A_{PL})^n_n` over the standard `n`-simplex :math:`\Delta^n`.
            For homogeneous elements :math:`\theta \in A_{PL}(p_n)`
            with :math:`n\neq p`, the integral is set to zero. Then, the map is extended to all :math:`(A_{PL})`
            by linearity.

            INPUT:

            - ``yi`` -- integer (optional, default: `0`); variable to reduce
            ``self`` before integration

            OUTPUT: a rational number;

            .. tab:: Sage

                EXAMPLES::

                The integral of the Whitney form::

                        sage: A = AplN(4)
                        sage: w = A.whitney_form()
                        sage: w
                        24*t4*y0*y1*y2*y3 - 24*t3*y0*y1*y2*y4 + 24*t2*y0*y1*y3*y4 - 24*t1*y0*y2*y3*y4 + 24*t0*y1*y2*y3*y4
                        sage: w.integral()
                        1

                The integral of a generic form of maximum degree::

                        sage: A = AplN(4)
                        sage: R = A.base_ring()
                        sage: A.inject_variables()
                        Defining y0, y1, y2, y3, y4
                        sage: R.inject_variables()
                        Defining t0, t1, t2, t3, t4
                        sage: theta = (t1**2-1)*A.whitney_form()
                        sage: theta
                        (24*t1^2*t4 - 24*t4)*y0*y1*y2*y3 + (-24*t1^2*t3 + 24*t3)*y0*y1*y2*y4 + (24*t1^2*t2 - 24*t2)*y0*y1*y3*y4 + (-24*t1^3 + 24*t1)*y0*y2*y3*y4 + (24*t0*t1^2 - 24*t0)*y1*y2*y3*y4
                        sage: theta.reduce(0)
                        (24*t1^2 - 24)*y1*y2*y3*y4
                        sage: theta.integral()
                        -14/15
                        sage: (factorial(4)*2)/factorial(2+4)
                        1/15
                        sage: (factorial(4)*2)/factorial(2+4)-1
                        -14/15

                The integral of an element of degree lower than the dimension of ``self.parent()``::

                        sage: A = AplN(4)
                        sage: R = A.base_ring()
                        sage: A.inject_variables()
                        Defining y0, y1, y2, y3, y4
                        sage: R.inject_variables()
                        Defining t0, t1, t2, t3, t4
                        sage: theta = t1*y0
                        sage: theta.integral()
                        0

                The integral of a non-homogeneous element::

                        sage: A = AplN(4)
                        sage: R = A.base_ring()
                        sage: A.inject_variables()
                        Defining y0, y1, y2, y3, y4
                        sage: R.inject_variables()
                        Defining t0, t1, t2, t3, t4
                        sage: theta = t1*y0 + y1*y2
                        sage: theta.integral()
                        0
                        sage: theta = t1*y0 + y1*y2 + A.whitney_form()
                        sage: theta.integral()
                        1

            """
            A = self.parent()
            voldeg = A.n
            if (self == A.zero()):
                return QQ(0)
            reduced_poly = self.reduce(yi)
            if (not reduced_poly):
                return QQ(0)
            elif not reduced_poly.is_homogeneous():
                if not voldeg in reduced_poly.homogeneous_components().keys():
                    return QQ(0)
            elif (reduced_poly.degree() != voldeg):
                return QQ(0)
                #raise ValueError(
                    #('The integral is defined for homogeneous polynomials of degree ' + str(voldeg)))
            coeff = reduced_poly.leading_coefficient()
            integrals = []
            for (i, m) in enumerate(coeff.monomials()):
                c = coeff.coefficients()[i]
                num = prod([factorial(i) for i in m.degrees()])
                den = factorial((sum(m.degrees()) + voldeg))
                integrals += [((c * num) / den)]
            return (((- 1) ** yi) * sum(integrals))

        @cached_method(do_pickle=True)
        def koszul(self):
            r"""
            Return the koszul differential of `self`.

            For the :math:`q`--form :math:`\omega \in (A_{PL})^q_n`:

            .. math::
                \omega = p(\overline{t}) \;y_{j_0} \wedge\cdots\wedge y_{j_{q-1}}

            the koszul differential :math:`\kappa: (A_{PL})^q_n \rightarrow (A_{PL})^{q-1}_n` is defined as

            .. math::

                \kappa (\omega) = p(\overline{t}) \sum_{j=0}^{q-1}(-1)^{j}t_{i_j}y_{i_0}\wedge\cdots\wedge\hat{y_{i_j}}\wedge\cdots\wedge y_{j_{q-1}}

            where :math:`p(\overline{t}) \in \mathbb{Q}[t_0,\dots,t_n]`.

            Let :math:`\omega,\theta \in (A_{PL})_n`, and :math:`\omega` defined as before such that
            :math:`q=|\omega|`, and :math:`r=|p(\overline{t})|`. Then, the koszul differential has the properties:

                - :math:`\kappa \circ \kappa = 0`,

                - :math:`(\kappa \circ d)(\omega) + (d \circ \kappa)(\omega) = (r+q)\omega`,

                - :math:`\kappa(\omega \wedge \theta ) = \kappa(\omega) \wedge \theta + (-1)^{|\omega|} \omega \wedge \kappa (\theta)`.


            OUTPUT: a differential :math:`(q-1)` --form.

            .. tab:: Sage

                EXAMPLES::

                This example illustrates the relation between the cochain differential and koszul differential::

                        sage: A = AplN(3)
                        sage: R = A.base_ring()
                        sage: A.inject_variables()
                        Defining
                        y0, y1, y2, y3
                        sage: R.inject_variables()
                        Defining
                        t0, t1, t2, t3
                        sage: p = t0 * t2 * y2 * y3
                        sage: p
                        t0*t2*y2*y3
                        sage: p.koszul().differential()+p.differential().koszul()
                        4*t0*t2*y2*y3
                        sage: (p.differential().koszul()+p.koszul().differential()).reduce(0) == (2+2)*p.reduce(0)
                        True

                This example illustrates the koszul differential of a wedge of forms::

                        sage: A = AplN(4)
                        sage: R = A.base_ring()
                        sage: A.inject_variables()
                        Defining y0, y1, y2, y3, y4
                        sage: R.inject_variables()
                        Defining t0, t1, t2, t3, t4
                        sage: p = t1*y2
                        sage: q = t2*y3*y4
                        sage: print(p.koszul()*q+((-1)**p.degree())*p*q.koszul().reduce(0) == (p*q).koszul().reduce(0))
                        True
                        sage: print(p.koszul().differential()+ p.differential().koszul() == (1+1)*p)
                        True
                        sage: print(q.koszul().differential()+ q.differential().koszul() == (1+2)*q)
                        True
            """

            return self.parent()._koszul_differential(self)

        @cached_method(do_pickle=True)
        def reduce(self, var_idx, label_ref=False):
            r"""
            Return the reduction of ``self`` by the relations:

            - :math:`t_i = 1-\sum_{j \neq i} t_j`,
            - :math:`y_i = -\sum_{j \neq i} y_j`.

            INPUT:

            - ``var_idx`` -- (integer or str). The index or the label of the variable to be reduced.

            - ``label_ref`` -- boolean (default: False); If ``True``, ``var_idx`` is considered as a string.

            OUTPUT: an element of ``self.parent()``

            .. tab:: Sage

                EXAMPLES::

                    sage: A = AplN(5)
                    sage: R = A.base_ring()
                    sage: A.inject_variables()
                    Defining y0, y1, y2, y3, y4, y5
                    sage: R.inject_variables()
                    Defining t0, t1, t2, t3, t4, t5
                    sage: theta = t0*y4
                    sage: theta.reduce(0)
                    (-t1 - t2 - t3 - t4 - t5 + 1)*y4
                    sage: theta = t1*y0
                    sage: theta.reduce(0)
                    -t1*y1 - t1*y2 - t1*y3 - t1*y4 - t1*y5

            """
            A = self.parent()
            if (self == A.zero()):
                return self
            if label_ref:
                i = A.labels.index(var_idx)
            else:
                i = var_idx
            if (not (0 <= i <= A.n)):
                raise ValueError('i must be in [0, n]')
            hcomp = self.homogeneous_components()
            reducedSelf = A.zero()
            for (deg, p) in hcomp.items():
                coeff_map = A._reduce_coeff_endomorphism(i)
                if (deg == 0):
                    return A(p.map_coefficients(coeff_map))
                if (p.degree() == (A.n + 1)):
                    return A.zero()
                reduced_poly = p.map_coefficients(coeff_map)
                result = A.zero()
                for term in reduced_poly.terms():
                    coeff = term.leading_coefficient()
                    mon = term.leading_monomial()
                    reduced_mon = A._reduce_monomial(mon, i, deg)
                    result += (coeff * reduced_mon)
                reducedSelf += result
            return reducedSelf


if (__name__ == '__main__'):
    None
